Added transformer for `likert` field
GFExcel/gf-entries-in-excel pull request #121
Opened 2022-01-02 18:15 UTC by doekenorg

This MR closes #82 

It adds a Field Transformer for the Likert field from the Gravity Forms Survey Plugin. 

This transformer has a `gfexcel_field_likert_use_score` hook that will output the field value as the score instead of the string value, when the resulting value is `true`. 

```php
// Let `likert` fields return their score.
add_filter('gfexcel_field_likert_use_score', '__return_true');
```

After merging https://wordpress.org/support/topic/survey-scores-per-entry/#post-13830055 can also be updated to include the new solution. Their solution should however keep working.

2022-01-02 21:35 UTC, doekenorg commented on src/Field/SurveyLikertField.php
> +	protected function hasMultipleRows(): bool {
meh, this can be `private`

2022-01-29 21:38 UTC, zackkatz requested changes

2022-01-29 21:38 UTC, zackkatz commented on src/Field/SurveyLikertField.php
> +		$value = $entry[ $input_id ?: $this->field->id ] ?? ':';
Instead of compact, let's shoot for simple notation. Please break into multiple lines.

2022-01-29 21:38 UTC, zackkatz commented on src/Field/SurveyLikertField.php
> +		return 0; // choice not found, so value is 0
This return value isn't defined as a possible return type in `AbstractField::getFieldValue()`.

2022-01-29 21:38 UTC, zackkatz commented
Just a couple little tweaks. Thanks, @doekenorg!

2022-01-29 22:02 UTC, merged